# Generated by Django 5.2.11 on 2026-05-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_broker',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='sharing_status',
            field=models.CharField(blank=True, choices=[('Living in', 'Yes, living in property'), ('Moving soon', 'Going within a month')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='deposit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('RENTAL', 'Rental (Full House)'), ('PG', 'PG / Co-living'), ('ROOMMATE', 'Looking for Roommate')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RENTED', 'Rented Out / Found')], default='PENDING', max_length=10),
        ),
    ]
