# Generated by Django 5.2.11 on 2026-05-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_property_is_broker_property_sharing_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='phone_primary',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='phone_secondary',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
