# Generated by Django 5.2.11 on 2026-05-08 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_property_owner_name_property_phone_primary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_properties', to=settings.AUTH_USER_MODEL),
        ),
    ]
