# Generated by Django 5.2.11 on 2026-05-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_property_favorited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='document_aadhaar',
            field=models.FileField(blank=True, null=True, upload_to='verification_docs/'),
        ),
        migrations.AddField(
            model_name='property',
            name='document_electricity',
            field=models.FileField(blank=True, null=True, upload_to='verification_docs/'),
        ),
        migrations.AddField(
            model_name='property',
            name='document_noc',
            field=models.FileField(blank=True, null=True, upload_to='verification_docs/'),
        ),
    ]
